"""Localized filler lines for the Telegram bot.

WAIT lines are shown the moment a message arrives (a placeholder deleted once the real
reply is ready). BUSY lines answer a message that lands while the previous one is still
being handled. Picked at random per message. Keyed by our four locales; the customer's
Telegram ``language_code`` selects the set. See ADR-0011.
"""

WAIT = {
    "en": [
        "One moment, I'm on it… 🙏",
        "Got it — thinking it through… ✨",
        "Just a sec, looking into that… 🔎",
        "On it! Give me a moment… ⏳",
        "Let me check that for you… 🙌",
        "A breath while I find the answer… 🌿",
        "Working on it right now… ⚙️",
        "Hold on, pulling that up… 📋",
        "Sec — putting this together… 🧩",
        "Looking into it for you… 👀",
        "Right away — one moment… 💫",
        "Let me think for a second… 💭",
        "Checking the details… 📝",
        "Almost there, just a moment… 🚀",
        "Give me a heartbeat… 💛",
        "On the case — one sec… 🕵️",
        "Let me get that sorted… 🛠️",
        "Finding the best answer… 🌟",
        "Two seconds, I promise… 😊",
        "Pulling it together now… 🧵",
        "Hang tight, nearly done… 🤞",
        "Just gathering the details… 📚",
        "Let me look that up… 🔍",
        "One sec while I check… ⏱️",
        "Thinking… won't be long… 🧠",
        "Bear with me a moment… 🐻",
        "Sorting that out for you… ✅",
        "Coming right up… ☕",
        "Let me make sure it's right… 🎯",
        "A moment to get this perfect… 💎",
        "On it — thanks for waiting… 🙏",
        "Quick look and I'll be back… 👋",
        "Checking everything for you… 📦",
        "Let me line that up… 📐",
        "Just a moment, please… 🌸",
        "Working through it now… 🔧",
        "Almost ready with your answer… ⌛",
        "Give me one little moment… 🐣",
        "Looking that over… 🧐",
        "I'm right here — one sec… 💬",
        "Let me dig that up for you… ⛏️",
        "Putting the pieces together… 🧩",
        "Won't keep you long… 🌈",
        "Fetching that now… 📡",
        "Let me double-check… ✔️",
        "Just a tick… 🐝",
        "On it, finding the details… 🗂️",
        "Moment please, almost there… 🏁",
        "Let me get you a clear answer… 🔆",
        "Right with you… 🤝",
    ],
    "ru": [
        "Минуточку, уже занимаюсь… 🙏",
        "Принял — думаю над ответом… ✨",
        "Секунду, сейчас посмотрю… 🔎",
        "Уже отвечаю, одну минуту… ⏳",
        "Дайте проверю это для вас… 🙌",
        "Немного терпения, ищу ответ… 🌿",
        "Работаю над этим прямо сейчас… ⚙️",
        "Секунду, подтягиваю информацию… 📋",
        "Минутку — собираю ответ… 🧩",
        "Смотрю для вас… 👀",
        "Сейчас всё сделаю, момент… 💫",
        "Дайте подумаю секунду… 💭",
        "Проверяю детали… 📝",
        "Почти готово, ещё мгновение… 🚀",
        "Одно мгновение… 💛",
        "Уже разбираюсь — секунду… 🕵️",
        "Сейчас всё улажу… 🛠️",
        "Ищу лучший ответ для вас… 🌟",
        "Две секунды, обещаю… 😊",
        "Собираю всё воедино… 🧵",
        "Подождите чуть-чуть, почти готово… 🤞",
        "Уточняю детали… 📚",
        "Дайте посмотрю… 🔍",
        "Секунду, проверяю… ⏱️",
        "Думаю… это ненадолго… 🧠",
        "Чуть-чуть терпения… 🐻",
        "Решаю это для вас… ✅",
        "Сейчас принесу ответ… ☕",
        "Дайте удостоверюсь, что всё верно… 🎯",
        "Момент, чтобы всё было идеально… 💎",
        "Уже занимаюсь — спасибо, что ждёте… 🙏",
        "Быстро гляну и вернусь… 👋",
        "Проверяю для вас всё… 📦",
        "Сейчас выстрою ответ… 📐",
        "Одну минуту, пожалуйста… 🌸",
        "Прорабатываю это сейчас… 🔧",
        "Почти готов ваш ответ… ⌛",
        "Дайте мне маленькую секундочку… 🐣",
        "Изучаю это… 🧐",
        "Я здесь — секунду… 💬",
        "Сейчас всё найду для вас… ⛏️",
        "Складываю кусочки вместе… 🧩",
        "Не задержу вас надолго… 🌈",
        "Уже подгружаю… 📡",
        "Дайте перепроверю… ✔️",
        "Один миг… 🐝",
        "Уже ищу детали… 🗂️",
        "Момент, почти на финише… 🏁",
        "Подготовлю для вас чёткий ответ… 🔆",
        "Уже с вами… 🤝",
    ],
    "es": [
        "Un momento, ya me ocupo… 🙏",
        "Entendido — lo estoy pensando… ✨",
        "Un segundo, lo reviso… 🔎",
        "¡Ya te respondo! Un momento… ⏳",
        "Déjame verlo para ti… 🙌",
        "Un respiro mientras busco… 🌿",
        "Trabajando en ello ahora… ⚙️",
        "Un segundo, lo busco… 📋",
        "Un momento — armo la respuesta… 🧩",
        "Mirándolo para ti… 👀",
        "Enseguida, un momento… 💫",
        "Déjame pensar un segundo… 💭",
        "Revisando los detalles… 📝",
        "Casi listo, un momento… 🚀",
        "Dame un instante… 💛",
        "En ello — un segundo… 🕵️",
        "Déjame resolverlo… 🛠️",
        "Buscando la mejor respuesta… 🌟",
        "Dos segundos, lo prometo… 😊",
        "Juntando todo ahora… 🧵",
        "Aguanta, casi termino… 🤞",
        "Reuniendo los detalles… 📚",
        "Déjame buscarlo… 🔍",
        "Un segundo mientras reviso… ⏱️",
        "Pensando… no tardo… 🧠",
        "Ten paciencia un momento… 🐻",
        "Resolviéndolo para ti… ✅",
        "Enseguida lo traigo… ☕",
        "Déjame asegurarme de que esté bien… 🎯",
        "Un momento para que quede perfecto… 💎",
        "En ello — gracias por esperar… 🙏",
        "Un vistazo y vuelvo… 👋",
        "Revisando todo para ti… 📦",
        "Déjame organizarlo… 📐",
        "Un momento, por favor… 🌸",
        "Trabajándolo ahora… 🔧",
        "Casi lista tu respuesta… ⌛",
        "Dame un instantito… 🐣",
        "Revisándolo… 🧐",
        "Aquí estoy — un segundo… 💬",
        "Déjame buscarlo para ti… ⛏️",
        "Uniendo las piezas… 🧩",
        "No te entretengo mucho… 🌈",
        "Cargándolo ahora… 📡",
        "Déjame verificar… ✔️",
        "Un instante… 🐝",
        "Buscando los detalles… 🗂️",
        "Un momento, casi llego… 🏁",
        "Te preparo una respuesta clara… 🔆",
        "Contigo enseguida… 🤝",
    ],
    "zh": [
        "稍等一下，马上就来…🙏",
        "收到——正在思考…✨",
        "稍等，我看一下…🔎",
        "马上回复你，请稍候…⏳",
        "让我帮你确认一下…🙌",
        "稍等片刻，正在查找…🌿",
        "正在处理中…⚙️",
        "稍等，正在调取…📋",
        "稍候——正在整理答案…🧩",
        "正在为你查看…👀",
        "马上好，请稍等…💫",
        "让我想一下…💭",
        "正在核对细节…📝",
        "快好了，请稍候…🚀",
        "给我一点点时间…💛",
        "正在处理——稍等…🕵️",
        "让我来解决…🛠️",
        "正在寻找最佳答案…🌟",
        "两秒钟，我保证…😊",
        "正在汇总…🧵",
        "请稍候，快完成了…🤞",
        "正在收集细节…📚",
        "让我查一下…🔍",
        "稍等，正在核对…⏱️",
        "思考中…不会太久…🧠",
        "请耐心稍候…🐻",
        "正在为你处理…✅",
        "答案马上送上…☕",
        "让我确认无误…🎯",
        "稍候，把它做到完美…💎",
        "正在处理——谢谢等待…🙏",
        "看一眼就回来…👋",
        "正在为你检查…📦",
        "让我整理一下…📐",
        "请稍等片刻…🌸",
        "正在仔细处理…🔧",
        "你的答案快好了…⌛",
        "给我一小会儿…🐣",
        "正在查看…🧐",
        "我在呢——稍等…💬",
        "让我为你找一下…⛏️",
        "正在拼凑信息…🧩",
        "不会耽误你太久…🌈",
        "正在加载…📡",
        "让我再核对一遍…✔️",
        "一瞬间…🐝",
        "正在查找细节…🗂️",
        "稍候，就快好了…🏁",
        "给你一个清晰的答复…🔆",
        "马上就来…🤝",
    ],
}

BUSY = {
    "en": [
        "Still on your last message — one moment! 🙏",
        "I'm finishing your previous question first… ⏳",
        "One thing at a time — almost done with the last one! 😊",
        "Hang on, I'm still answering the one before… ✋",
        "Give me a sec to wrap up the previous message… 🌀",
        "Still working on your earlier note — be right with you! 🙌",
        "Let me finish the first one, then I'm all yours… 💛",
        "Almost done with the previous — thanks for your patience! 🤞",
        "I haven't forgotten — just finishing the last reply… ✨",
        "One moment, still on the message before this… ⌛",
        "Wrapping up your last question first… 📝",
        "Hold that thought — finishing the previous one! 💭",
        "I'm a bit behind — still on the earlier message… 🐢",
        "Right after I finish the one before… 🔜",
        "Still typing the last answer — won't be long! ⌨️",
        "Let me catch up on the previous message first… 🏃",
        "Bear with me — completing your earlier request… 🐻",
        "Almost there with the first message… 🎯",
        "One sec, finishing what you asked before… 🧩",
        "I'm on the previous one — back to this in a moment! 🔄",
        "Just closing out your last message… ✅",
        "Hold on — I owe you an answer to the first one! 💬",
        "Still cooking the previous reply… 🍳",
        "Let me finish that thought, then yours… 🌟",
        "Patience please — wrapping the earlier one! 🙏",
        "I'll get to this right after the previous… ➡️",
        "Give me a moment to finish the first message… ⏱️",
        "Still here — just completing the one before… 👀",
        "One at a time so I get it right — almost done! 🎯",
        "Finishing your previous note, then this… 📋",
        "Hang tight, the earlier reply is nearly ready… 🚀",
        "Let me wrap the last one up properly… 💎",
        "Still on it — your first message comes first! 1️⃣",
        "A moment — completing the previous answer… 🌿",
        "I read this — finishing the earlier one first… 📨",
        "Nearly done with your last question… 🔚",
        "Steady — closing out the previous message… ⚓",
        "I'm with the first message — right back! 🔙",
        "Let me finish replying, then I'll take this… ✍️",
        "Almost wrapped the previous — one moment! 🎁",
        "Still answering before — thanks for waiting! 🙏",
        "Give me a breath to finish the last one… 🌬️",
        "On the earlier message — this is next! ⏭️",
        "One more moment on the previous reply… ✨",
        "Hold on, finishing your first request… 🛎️",
        "I've got both — just the first one first! 🤝",
        "Tidying up the previous answer… 🧹",
        "Almost free — wrapping the earlier one! 🆓",
        "Sit tight, completing the message before… 🪑",
        "Right after this previous one, promise! 🤙",
    ],
    "ru": [
        "Ещё дорабатываю прошлое сообщение — минутку! 🙏",
        "Сначала закончу ваш предыдущий вопрос… ⏳",
        "По одному — почти закончил с прошлым! 😊",
        "Секунду, я ещё отвечаю на предыдущее… ✋",
        "Дайте мне завершить прошлое сообщение… 🌀",
        "Ещё работаю над вашим прошлым вопросом — скоро вернусь! 🙌",
        "Закончу первое, и я весь ваш… 💛",
        "Почти готово с предыдущим — спасибо за терпение! 🤞",
        "Я не забыл — просто доделываю прошлый ответ… ✨",
        "Минутку, всё ещё на сообщении до этого… ⌛",
        "Завершаю ваш прошлый вопрос… 📝",
        "Придержите мысль — доделываю предыдущее! 💭",
        "Немного отстаю — ещё на прошлом сообщении… 🐢",
        "Сразу после того, как закончу предыдущее… 🔜",
        "Ещё печатаю прошлый ответ — это ненадолго! ⌨️",
        "Дайте догнать прошлое сообщение… 🏃",
        "Потерпите — завершаю ваш прошлый запрос… 🐻",
        "Почти готово с первым сообщением… 🎯",
        "Секунду, заканчиваю то, что вы спросили ранее… 🧩",
        "Я на предыдущем — вернусь к этому через миг! 🔄",
        "Просто закрываю ваше прошлое сообщение… ✅",
        "Секунду — за мной ответ на первое! 💬",
        "Ещё готовлю предыдущий ответ… 🍳",
        "Дайте закончить ту мысль, потом вашу… 🌟",
        "Немного терпения — завершаю прошлое! 🙏",
        "Возьмусь за это сразу после предыдущего… ➡️",
        "Дайте момент закончить первое сообщение… ⏱️",
        "Я здесь — просто доделываю прошлое… 👀",
        "По одному, чтобы всё было верно — почти готово! 🎯",
        "Завершаю ваше прошлое сообщение, потом это… 📋",
        "Подождите, прошлый ответ почти готов… 🚀",
        "Дайте как следует завершить прошлое… 💎",
        "Ещё на нём — ваше первое сообщение в приоритете! 1️⃣",
        "Момент — завершаю предыдущий ответ… 🌿",
        "Я прочитал — сначала доделаю прошлое… 📨",
        "Почти закончил с вашим прошлым вопросом… 🔚",
        "Спокойно — закрываю предыдущее сообщение… ⚓",
        "Я на первом сообщении — сейчас вернусь! 🔙",
        "Дайте дописать ответ, потом возьмусь за это… ✍️",
        "Почти завершил предыдущее — минутку! 🎁",
        "Ещё отвечаю на прошлое — спасибо, что ждёте! 🙏",
        "Дайте вдохнуть и закончить прошлое… 🌬️",
        "На прошлом сообщении — это следующее! ⏭️",
        "Ещё момент на предыдущий ответ… ✨",
        "Секунду, заканчиваю ваш первый запрос… 🛎️",
        "Вижу оба — просто сначала первое! 🤝",
        "Привожу в порядок прошлый ответ… 🧹",
        "Почти освободился — завершаю прошлое! 🆓",
        "Посидите, доделываю сообщение до этого… 🪑",
        "Сразу после этого предыдущего, обещаю! 🤙",
    ],
    "es": [
        "Sigo con tu mensaje anterior — ¡un momento! 🙏",
        "Primero termino tu pregunta anterior… ⏳",
        "Una cosa a la vez — ¡casi termino la anterior! 😊",
        "Espera, aún respondo la de antes… ✋",
        "Dame un segundo para cerrar el mensaje anterior… 🌀",
        "Sigo con tu nota anterior — ¡vuelvo enseguida! 🙌",
        "Déjame terminar la primera y soy todo tuyo… 💛",
        "Casi termino la anterior — ¡gracias por la paciencia! 🤞",
        "No me olvidé — termino la respuesta anterior… ✨",
        "Un momento, sigo en el mensaje anterior… ⌛",
        "Cerrando tu pregunta anterior… 📝",
        "Guarda esa idea — ¡termino la anterior! 💭",
        "Voy un poco atrás — aún en el mensaje anterior… 🐢",
        "Justo después de terminar la anterior… 🔜",
        "Aún escribo la respuesta anterior — ¡no tardo! ⌨️",
        "Déjame ponerme al día con el mensaje anterior… 🏃",
        "Ten paciencia — completo tu pedido anterior… 🐻",
        "Casi listo con el primer mensaje… 🎯",
        "Un segundo, termino lo que pediste antes… 🧩",
        "Estoy en la anterior — ¡vuelvo a esta en un momento! 🔄",
        "Cerrando tu último mensaje… ✅",
        "Espera — ¡te debo la respuesta de la primera! 💬",
        "Aún cocino la respuesta anterior… 🍳",
        "Déjame terminar esa idea, luego la tuya… 🌟",
        "Paciencia — ¡cerrando la anterior! 🙏",
        "Voy con esto justo después de la anterior… ➡️",
        "Dame un momento para terminar el primer mensaje… ⏱️",
        "Aquí estoy — solo completo la de antes… 👀",
        "Una a la vez para hacerlo bien — ¡casi! 🎯",
        "Termino tu mensaje anterior y luego este… 📋",
        "Aguanta, la respuesta anterior casi está… 🚀",
        "Déjame cerrar bien la anterior… 💎",
        "Sigo ahí — ¡tu primer mensaje va primero! 1️⃣",
        "Un momento — completo la respuesta anterior… 🌿",
        "Lo leí — primero termino la anterior… 📨",
        "Casi listo con tu pregunta anterior… 🔚",
        "Tranquilo — cierro el mensaje anterior… ⚓",
        "Estoy en el primer mensaje — ¡ya vuelvo! 🔙",
        "Déjame terminar de responder y tomo este… ✍️",
        "Casi cierro la anterior — ¡un momento! 🎁",
        "Aún respondo la anterior — ¡gracias por esperar! 🙏",
        "Dame un respiro para terminar la anterior… 🌬️",
        "En el mensaje anterior — ¡este es el siguiente! ⏭️",
        "Un momento más con la respuesta anterior… ✨",
        "Un segundo, termino tu primer pedido… 🛎️",
        "Tengo los dos — ¡solo el primero primero! 🤝",
        "Ordenando la respuesta anterior… 🧹",
        "Casi libre — ¡cerrando la anterior! 🆓",
        "Quédate, completo el mensaje anterior… 🪑",
        "Justo después de esta anterior, ¡lo prometo! 🤙",
    ],
    "zh": [
        "还在处理你上一条消息——稍等一下！🙏",
        "我先完成你之前的问题…⏳",
        "一次一件——上一条快好了！😊",
        "稍等，我还在回复上一条…✋",
        "给我一秒收尾上一条消息…🌀",
        "还在处理你之前的留言——马上回来！🙌",
        "让我先完成第一条，然后全力为你…💛",
        "上一条快完成了——谢谢耐心！🤞",
        "我没忘——只是在收尾上一条回复…✨",
        "稍等，还在之前那条消息上…⌛",
        "正在收尾你上一条问题…📝",
        "先记住这个——我在完成上一条！💭",
        "我稍微慢了点——还在之前那条…🐢",
        "等我完成上一条之后就来…🔜",
        "还在打上一条答案——不会太久！⌨️",
        "让我先跟上之前那条消息…🏃",
        "请耐心——正在完成你之前的请求…🐻",
        "第一条快好了…🎯",
        "稍等，正在完成你之前问的…🧩",
        "我在处理上一条——马上回到这条！🔄",
        "正在结束你上一条消息…✅",
        "稍等——我还欠你第一条的答复！💬",
        "上一条回复还在准备中…🍳",
        "让我先完成那个想法，再到你的…🌟",
        "请耐心——正在收尾上一条！🙏",
        "处理完上一条我就来…➡️",
        "给我一点时间完成第一条消息…⏱️",
        "我在呢——只是在完成之前那条…👀",
        "一条一条来才能做好——快了！🎯",
        "先完成你上一条消息，再到这条…📋",
        "稍候，上一条答复快好了…🚀",
        "让我把上一条好好收尾…💎",
        "还在上面——你的第一条消息优先！1️⃣",
        "稍等——正在完成上一条回复…🌿",
        "我看到了——先完成之前那条…📨",
        "你上一条问题快好了…🔚",
        "别急——正在结束上一条消息…⚓",
        "我在第一条消息上——马上回来！🔙",
        "让我先回复完，再处理这条…✍️",
        "上一条快收尾了——稍等！🎁",
        "还在回复上一条——谢谢等待！🙏",
        "让我喘口气完成上一条…🌬️",
        "在上一条消息上——这条是下一个！⏭️",
        "上一条回复再等一下…✨",
        "稍等，正在完成你的第一个请求…🛎️",
        "两条我都看到了——只是先处理第一条！🤝",
        "正在整理上一条答复…🧹",
        "快忙完了——正在收尾上一条！🆓",
        "坐稳，正在完成之前那条消息…🪑",
        "处理完这条之前的就来，我保证！🤙",
    ],
}
